export interface InspirationImage {
  id: string
  title: string
  room: string
  style: string
  color: string
  material: string
  image: string
  products: string[]
  customerName?: string
  location?: string
}

export const inspirationImages: InspirationImage[] = [
  {
    id: "1",
    title: "Cozy Living Room with Golden Retriever",
    room: "Living Room",
    style: "Mid-Century Modern",
    color: "Blush",
    material: "Fabric",
    image: "/cozy-living-room-blush-pink-sectional-sofa-golden-.jpg",
    products: ["Elda Sectional Sofa", "Fjord Coffee Table"],
    customerName: "Sarah M.",
    location: "Portland, OR",
  },
  {
    id: "2",
    title: "Teal Velvet Statement Sofa",
    room: "Living Room",
    style: "Contemporary",
    color: "Teal",
    material: "Velvet",
    image: "/elegant-living-room-deep-teal-velvet-sofa-botanica.jpg",
    products: ["Skagen Three-Seater", "Birka Ottoman"],
    customerName: "Michael T.",
    location: "Austin, TX",
  },
  {
    id: "3",
    title: "Sunlit Rust Orange Corner",
    room: "Living Room",
    style: "Bohemian",
    color: "Rust",
    material: "Fabric",
    image: "/bright-sunny-living-room-rust-orange-sectional-sof.jpg",
    products: ["Hedda Modular Sectional", "Visby Side Table"],
    customerName: "Emma L.",
    location: "Denver, CO",
  },
  {
    id: "4",
    title: "Moody Green Library",
    room: "Home Office",
    style: "Traditional",
    color: "Green",
    material: "Velvet",
    image: "/moody-dark-green-velvet-sofa-home-library-dark-wal.jpg",
    products: ["Vasa Chesterfield Sofa", "Rune Bookcase"],
    customerName: "David K.",
    location: "Chicago, IL",
  },
  {
    id: "5",
    title: "Minimalist Bedroom Retreat",
    room: "Bedroom",
    style: "Minimalist",
    color: "Gray",
    material: "Linen",
    image: "/serene-minimalist-bedroom-gray-linen-upholstered-b.jpg",
    products: ["Saga Platform Bed", "Eira Nightstand"],
    customerName: "Jessica R.",
    location: "Seattle, WA",
  },
  {
    id: "6",
    title: "Warm Leather Den",
    room: "Living Room",
    style: "Mid-Century Modern",
    color: "Brown",
    material: "Leather",
    image: "/warm-cozy-den-cognac-brown-leather-sofa-mid-centur.jpg",
    products: ["Thor Leather Sofa", "Odin Lounge Chair"],
    customerName: "James W.",
    location: "Nashville, TN",
  },
  {
    id: "7",
    title: "A-Frame Living Space",
    room: "Living Room",
    style: "Rustic",
    color: "Olive",
    material: "Velvet",
    image: "/a-frame-cabin-living-room-olive-green-velvet-sofa-.jpg",
    products: ["Frey Curved Sofa", "Yggdrasil Coffee Table"],
    customerName: "Alex P.",
    location: "Aspen, CO",
  },
  {
    id: "8",
    title: "Dining Room with Cat",
    room: "Dining Room",
    style: "Scandinavian",
    color: "Navy",
    material: "Fabric",
    image: "/bright-scandinavian-dining-room-navy-blue-upholste.jpg",
    products: ["Sigrid Dining Chair Set", "Harald Dining Table"],
    customerName: "Nina S.",
    location: "Minneapolis, MN",
  },
  {
    id: "9",
    title: "Pink Accent Reading Nook",
    room: "Living Room",
    style: "Eclectic",
    color: "Pink",
    material: "Velvet",
    image: "/cozy-reading-nook-dusty-pink-velvet-armchair-books.jpg",
    products: ["Freya Accent Chair", "Mimir Floor Lamp"],
    customerName: "Olivia C.",
    location: "Brooklyn, NY",
  },
  {
    id: "10",
    title: "Sunny Breakfast Corner",
    room: "Dining Room",
    style: "Contemporary",
    color: "Yellow",
    material: "Fabric",
    image: "/bright-breakfast-nook-yellow-upholstered-bench-rou.jpg",
    products: ["Sol Dining Bench", "Dagny Round Table"],
    customerName: "Rachel B.",
    location: "San Diego, CA",
  },
  {
    id: "11",
    title: "Mocha Mousse Master Suite",
    room: "Bedroom",
    style: "Modern",
    color: "Brown",
    material: "Velvet",
    image: "/luxurious-master-bedroom-mocha-brown-velvet-headbo.jpg",
    products: ["Pama Upholstered Bed", "Natt Dresser"],
    customerName: "Lauren H.",
    location: "Atlanta, GA",
  },
  {
    id: "12",
    title: "Family Room with Kids",
    room: "Living Room",
    style: "Transitional",
    color: "Beige",
    material: "Performance Fabric",
    image: "/family-friendly-living-room-beige-performance-fabr.jpg",
    products: ["Famn Modular Sectional", "Barn Storage Ottoman"],
    customerName: "The Martinez Family",
    location: "Phoenix, AZ",
  },
  {
    id: "13",
    title: "Sophisticated Home Office",
    room: "Home Office",
    style: "Contemporary",
    color: "Charcoal",
    material: "Leather",
    image: "/sophisticated-home-office-charcoal-leather-executi.jpg",
    products: ["Styrke Office Chair", "Kunskap Desk"],
    customerName: "Thomas G.",
    location: "Boston, MA",
  },
  {
    id: "14",
    title: "Coastal Blue Bedroom",
    room: "Bedroom",
    style: "Coastal",
    color: "Blue",
    material: "Linen",
    image: "/coastal-bedroom-light-blue-linen-bedding-white-fur.jpg",
    products: ["Hav Platform Bed", "Strand Nightstand"],
    customerName: "Katie M.",
    location: "Miami, FL",
  },
  {
    id: "15",
    title: "Vintage-Inspired Living Room",
    room: "Living Room",
    style: "Vintage",
    color: "Rose",
    material: "Velvet",
    image: "/vintage-inspired-living-room-dusty-rose-velvet-sof.jpg",
    products: ["Antika Tufted Sofa", "Arv Side Table"],
    customerName: "Grace F.",
    location: "Savannah, GA",
  },
  {
    id: "16",
    title: "Industrial Loft Space",
    room: "Living Room",
    style: "Industrial",
    color: "Tan",
    material: "Leather",
    image: "/placeholder.svg?height=600&width=600",
    products: ["Stål Leather Sectional", "Järn Coffee Table"],
    customerName: "Marcus D.",
    location: "Detroit, MI",
  },
]

export const rooms = ["All Rooms", "Living Room", "Bedroom", "Dining Room", "Home Office"]

export const styles = [
  "All Styles",
  "Mid-Century Modern",
  "Contemporary",
  "Scandinavian",
  "Bohemian",
  "Minimalist",
  "Modern",
  "Transitional",
  "Eclectic",
  "Traditional",
  "Rustic",
  "Coastal",
  "Vintage",
  "Industrial",
]

export const colors = [
  "All Colors",
  "Blush",
  "Teal",
  "Rust",
  "Green",
  "Gray",
  "Brown",
  "Olive",
  "Navy",
  "Pink",
  "Yellow",
  "Beige",
  "Charcoal",
  "Blue",
  "Rose",
  "Tan",
]

export const materials = ["All Materials", "Fabric", "Velvet", "Leather", "Linen", "Performance Fabric"]
